# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mult_pois_mcmc <- function(data_list, initial_list, prior_list, block, begin_group_update, burn, iter) {
    .Call('multAbund_mult_pois_mcmc', PACKAGE = 'multAbund', data_list, initial_list, prior_list, block, begin_group_update, burn, iter)
}

mult_occ_mcmc <- function(data_list, initial_list, prior_list, block, begin_group_update, burn, iter) {
    .Call('multAbund_mult_occ_mcmc', PACKAGE = 'multAbund', data_list, initial_list, prior_list, block, begin_group_update, burn, iter)
}

mult_zip_mcmc <- function(data_list, initial_list, prior_list, block, begin_group_update, burn, iter) {
    .Call('multAbund_mult_zip_mcmc', PACKAGE = 'multAbund', data_list, initial_list, prior_list, block, begin_group_update, burn, iter)
}

pois_reg_mcmc <- function(data_list, prior_list, initial_list, block, burn, iter) {
    .Call('multAbund_pois_reg_mcmc', PACKAGE = 'multAbund', data_list, prior_list, initial_list, block, burn, iter)
}

probit_reg_mcmc <- function(data_list, prior_list, initial_list, burn, iter) {
    .Call('multAbund_probit_reg_mcmc', PACKAGE = 'multAbund', data_list, prior_list, initial_list, burn, iter)
}

zip_reg_mcmc <- function(data_list, prior_list, initial_list, block, burn, iter) {
    .Call('multAbund_zip_reg_mcmc', PACKAGE = 'multAbund', data_list, prior_list, initial_list, block, burn, iter)
}

