# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mult_abund_mcmc <- function(data_list, pred_list, initial_vals, phi_beta, mu_beta, phi_omega, df_omega, a_alpha, b_alpha, phi_sigma, df_sigma, block, begin_group_update, burn, iter) {
    .Call('multAbund_mult_abund_mcmc', PACKAGE = 'multAbund', data_list, pred_list, initial_vals, phi_beta, mu_beta, phi_omega, df_omega, a_alpha, b_alpha, phi_sigma, df_sigma, block, begin_group_update, burn, iter)
}

mult_occ_mcmc <- function(data_list, pred_list, initial_vals, phi_beta, mu_beta, phi_omega, df_omega, a_alpha, b_alpha, block, begin_group_update, burn, iter) {
    .Call('multAbund_mult_occ_mcmc', PACKAGE = 'multAbund', data_list, pred_list, initial_vals, phi_beta, mu_beta, phi_omega, df_omega, a_alpha, b_alpha, block, begin_group_update, burn, iter)
}

pois_reg_mcmc <- function(data_list, pred_list, phi_beta, mu_beta, phi_sigma, df_sigma, block, burn, iter) {
    .Call('multAbund_pois_reg_mcmc', PACKAGE = 'multAbund', data_list, pred_list, phi_beta, mu_beta, phi_sigma, df_sigma, block, burn, iter)
}

